baseURL = "/"
languageCode = "en-us"
title = "Shafik"
copyright = "Mohd. Shafikur Rahman"
theme="shafikshaon_hugo_portfolio"
googleAnalytics = "UA-42600555-6"
paginate = "5"
categories = []

[taxonomies]
    categories  = "categories"

[Author]
    name = "Mohd. Shafikur Rahman"
    profile = "https://shafik.xyz"

[Taxonomies]
    tag = "tags"
    category = "categories"

[Params]
    intro = true
    headline = "Shafik"
    description = ""
    github = "https://github.com/shafikshaon"
    gitlab = "https://gitlab.com/shafikshaon"
    linkedin = "https://linkedin.com/in/shafikshaon/"
    twitter = "https://twitter.com/shafikshaon"
    facebook = "https://facebook.com/shafikshaon"
    stackoverflow = "https://stackoverflow.com/users/4751726/"
    email = "shafikshaon@gmail.com"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareLinkedIn = true
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""
    exponeaJsUrl = ""
    exponeaTarget = ""
    exponeaToken = ""
    exponeaTrackVisits = false
    showRelatedPosts = true
    readingTime = true
    wordCount = true
    tags_counter = false
    readingTimeText = "Estimated reading time:"

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[menu]
  [[menu.main]]
      name = "Me"
      url = "/me/"
      weight = 1

  [[menu.main]]
      name = "Articles"
      url = "/posts/"
      weight = 2

  [[menu.main]]
      name = "Contact"
      url = "/contact/"
      weight = 3

#navbar dropdown
#    [[menu.main]]
#        identifier = "samples"
#        name = "Samples"
#        weight = 2
#
#    [[menu.main]]
#        parent = "samples"
#        name = "Big Image Sample"
#        url = "post/2017-03-07-bigimg-sample"
#        weight = 1
#
#    [[menu.main]]
#        parent = "samples"
#        name = "Math Sample"
#        url = "post/2017-03-05-math-sample"
#        weight = 2
#
#    [[menu.main]]
#        parent = "samples"
#        name = "Code Sample"
#        url = "post/2016-03-08-code-sample"
#        weight = 3
#
#    [[menu.main]]
#        name = "Tags"
#        url = "tags"
#        weight = 3
