baseURL = "/"
languageCode = "en-us"
title = "Shafik"
copyright = "Mohd. Shafikur Rahman"
theme="shafikshaon_hugo_portfolio"
googleAnalytics = "UA-42600555-6"
paginate = "5"
categories = ["Programming", "DevOps", "Development"]
disqusShortname = "shafik-xyz"
enableRobotsTXT = false

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[languages.en.params.search]
    enable = true
    # type of search engine ("lunr", "algolia")
    type = "algolia"
    # max index length of the chunked content
    contentLength = 4000
    # placeholder of the search bar
    placeholder = ""
    # max number of results length
    maxResultLength = 10
    # snippet length of the result
    snippetLength = 30
    # HTML tag name of the highlight part in results
    highlightTag = "em"
    # whether to use the absolute URL based on the baseURL in search index
    absoluteURL = false
    [languages.en.params.search.algolia]
      index = "index.en"
      appID = "PASDMWALPK"
      searchKey = "b42948e51daaa93df92381c8e2ac0f93"

[taxonomies]
    categories  = "categories"

[Author]
    name = "Mohd. Shafikur Rahman"
    profile = "https://shafik.xyz"

[Taxonomies]
    tag = "tags"
    category = "categories"

[Params]
    intro = true
    headline = "Shafik"
    description = ""
    github = "https://github.com/shafikshaon"
    gitlab = "https://gitlab.com/shafikshaon"
    linkedin = "https://linkedin.com/in/shafikshaon/"
    twitter = "https://twitter.com/shafikshaon"
    facebook = "https://facebook.com/shafikshaon"
    stackoverflow = "https://stackoverflow.com/users/4751726/"
    email = "shafikshaon@gmail.com"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareLinkedIn = true
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""
    exponeaJsUrl = ""
    exponeaTarget = ""
    exponeaToken = ""
    exponeaTrackVisits = false
    showRelatedPosts = true
    readingTime = true
    wordCount = true
    tags_counter = false
    readingTimeText = "Estimated reading time:"

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[menu]
#   [[menu.main]]
#       name = "Me"
#       url = "/me/"
#       weight = 1

  [[menu.main]]
      name = "Posts"
      url = "/posts/"
      weight = 2
#
#   [[menu.main]]
#       name = "Tags"
#       url = "/tags/"
#       weight = 3

  [[menu.main]]
      name = "Contact"
      url = "/contact/"
      weight = 4
